# Generated by Django 6.0.4 on 2026-04-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
