# Generated by Django 6.0.4 on 2026-05-27 22:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0003_alter_viaje_asientos_disponibles_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_reporte', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('EN_REVISION', 'En revisión por administrador'), ('RESUELTO', 'Caso resuelto')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(help_text='Descripción detallada de la infracción o problema')),
                ('prueba', models.ImageField(blank=True, null=True, upload_to='evidencias_reportes/')),
                ('reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(help_text='Calificación del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resenia', models.TextField(blank=True, help_text='Comentario opcional sobre el viaje', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_dadas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='viajes.viaje')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('viaje', 'evaluador', 'evaluado'), name='unica_evaluacion_por_viaje')],
            },
        ),
    ]
