# Generated by Django 6.0.4 on 2026-05-29 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
        ('viajes', '0004_alter_viaje_asientos_disponibles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reporte',
            constraint=models.UniqueConstraint(fields=('viaje', 'reportador', 'reportado'), name='unico_reporte_por_viaje'),
        ),
    ]
