# Generated by Django 6.0.4 on 2026-05-01 03:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_viaje', models.CharField(choices=[('NO_INICIADO', 'No iniciado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='NO_INICIADO', max_length=20)),
                ('zona_origen', models.CharField(max_length=50)),
                ('zona_destino', models.CharField(max_length=50)),
                ('fecha_hora_salida', models.DateTimeField(help_text='Formato: DD/MM/YYYY HH:MM', verbose_name='Fecha y hora de salida')),
                ('asientos_disponibles', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.vehiculo')),
            ],
        ),
    ]
