# Generated by Django 6.0.4 on 2026-05-22 13:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='asientos_disponibles',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_solicitud', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('CANCELADA', 'Cancelada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='EN_ESPERA', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='viajes.viaje')),
            ],
            options={
                'unique_together': {('viaje', 'pasajero')},
            },
        ),
    ]
