# Generated by Django 6.0.4 on 2026-05-29 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_alter_viaje_asientos_disponibles_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='asientos_disponibles',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
