# Generated by Django 6.0.4 on 2026-05-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_alter_viaje_asientos_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Costo ilustrativo del viaje (Ej: 1.50)', max_digits=5),
        ),
    ]
