# Generated by Django 6.0.4 on 2026-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_viaje_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='notas',
            field=models.TextField(blank=True, help_text='Especifica reglas de convivencia o detalles del punto de encuentro.', null=True, verbose_name='Notas y Reglas del viaje'),
        ),
    ]
