"""
Django settings for URide project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*==a5yv#&l*^xoh(vr#kv_px4la7*vqr=e0q*4786x+2lcq3ya"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["10.79.19.141", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "viajes.apps.ViajesConfig",
    "cuentas.apps.CuentasConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "URide.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "URide.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "uride_db",
        "USER": "uride_admin",
        "PASSWORD": os.getenv("PASSWORD"),
        "HOST": "localhost",
        "PORT": "5432",  # El puerto por defecto de Postgres
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-ec"

TIME_ZONE = "America/Guayaquil"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# 1. MEDIA_URL: Es la URL con la que los navegadores solicitaran las paginas
MEDIA_URL = "/media/"

# 2. MEDIA_ROOT: Es la ruta física real en la computadora
MEDIA_ROOT = BASE_DIR / "media"

#

AUTH_USER_MODEL = "cuentas.Usuario"  # Django usara nuestro modelo de Usuario creado por nosotros y no el
# que viene por defecto


LOGIN_REDIRECT_URL = "/"  # Después del login, llévalo al Home
LOGOUT_REDIRECT_URL = "/login/"  # Después de cerrar sesión, llévalo al login

# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Configuración para enviar correos reales (SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# El correo desde el cual enviarás los mensajes
EMAIL_HOST_USER = "pablotp404@gmail.com"

# La clave de 16 letras de google
EMAIL_HOST_PASSWORD = os.getenv("GOOGLEPASSWORD")

# El nombre que verán los usuarios al recibir el correo
DEFAULT_FROM_EMAIL = "U-Ride Admin <pablotp404@gmail.com>"
